name: access-nri-intake-test
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python==3.11
  - pillow
  - matplotlib
  - ipywidgets
  - astropy
  - tqdm
  - netcdf4
  - pre-commit
  - pytest
  - xarray
  - pip
  - pip:
    - lavavu-osmesa
    - moderngl
    - codecov
    - pytest-cov
