name: access-nri-intake-test
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python>=3.9.2 # see https://github.com/dask/distributed/issues/7956
  - pillow
  - matplotlib
  - ipywidgets
  - astropy
  - tqdm
  - netcdf4
  - pre-commit
  - pytest
  - xarray
  - pip
  - pip:
    - lavavu
    - codecov
    - pytest-cov
