name: Image Tests

#Run on pushed commits but not tags
#https://github.community/t/dont-run-on-tag-creation/137469/7
on:
  push:
    branches:
      - '**'

jobs:
  build:
    # Use vis server to run
    runs-on: [self-hosted]
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-24.04]
        #python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- name: Set up Python
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      #NOTE: tests should pass in all timezones, this is a bug in accessvis
      - name: Change time zone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Australia/Melbourne"
      #- name: Set up linux dependencies
      #  if: runner.os == 'Linux'
      #  run: |
      #    sudo apt-get update -y
      #    sudo apt-get install -y libosmesa6 libosmesa6-dev libglapi-mesa mesa-common-dev libglx-mesa0 libgl1-mesa-dri libgl-dev libglx-dev libgl1 libglx0 libglvnd0
      - name: Build/install
        run: python -m pip install .
      - name: Run headless test
        env:
          LV_CONTEXT: moderngl
          LV_ECHO_FAIL: 1
          LV_ARGS: -v
        run: |
          python -m pip install moderngl freezegun
          git clone -b tests --depth 1 https://github.com/ACCESS-NRI/ACCESS-Visualisation-Recipes.git
          cd ACCESS-Visualisation-Recipes/tests
          python tests.py thumbs

